# Generated by Django 5.2.1 on 2025-09-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('publication', models.TextField()),
                ('author', models.TextField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('display_score', models.TextField(blank=True, null=True)),
                ('fresh_rotten', models.BooleanField()),
                ('date_published', models.DateField()),
                ('quote', models.TextField()),
                ('platform', models.TextField()),
                ('url_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
