# Generated by Django 5.2.1 on 2025-09-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewinfo',
            name='url_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
