# Generated by Django 5.2.1 on 2025-09-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0002_alter_reviewinfo_url_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewinfo',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
