# Generated by Django 5.2.1 on 2025-09-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0003_alter_reviewinfo_url_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('title', models.TextField()),
                ('mock_mc', models.FloatField(blank=True)),
                ('all_percent', models.FloatField(blank=True)),
                ('all_rating', models.TextField(blank=True)),
                ('tc_percent', models.FloatField(blank=True)),
                ('tc_rating', models.TextField(blank=True)),
                ('user_percent', models.FloatField(blank=True)),
                ('user_rating', models.TextField(blank=True)),
                ('critics_consensus', models.TextField(blank=True, max_length=100000, null=True)),
                ('all_symbol', models.FloatField(blank=True)),
                ('tc_symbol', models.FloatField(blank=True)),
                ('user_symbol', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaBars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('score_list', models.JSONField()),
            ],
        ),
    ]
