# Generated by Django 5.2.1 on 2025-09-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0004_gamescores_metabars'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('slug', models.TextField()),
                ('name', models.TextField()),
                ('release_date', models.DateField(blank=True)),
                ('tba', models.BooleanField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('platforms', models.TextField(blank=True)),
                ('developers', models.TextField(blank=True)),
                ('genres', models.TextField(blank=True)),
                ('publishers', models.TextField(blank=True)),
                ('esrb_rating', models.TextField(blank=True)),
                ('poster_link', models.URLField(blank=True)),
                ('critics_score', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
