# Generated by Django 5.2.1 on 2025-09-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0005_gameinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='poster_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
