# Generated by Django 5.2.1 on 2025-09-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0006_alter_gameinfo_poster_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='developers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='esrb_rating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='genres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='platforms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='publishers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='slug',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='tba',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
