# Generated by Django 5.2.1 on 2025-09-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0007_alter_gameinfo_developers_alter_gameinfo_esrb_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
