# Generated by Django 5.2.1 on 2025-09-07 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0008_alter_gameinfo_id_number_alter_gameinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewinfo',
            name='id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newGameoMeter.gameinfo'),
        ),
    ]
