# Generated by Django 5.2.1 on 2025-09-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0009_alter_reviewinfo_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescores',
            name='mock_mc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
