# Generated by Django 5.2.1 on 2025-09-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0010_alter_gamescores_mock_mc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescores',
            name='all_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='all_rating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='tc_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='tc_rating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='user_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='user_rating',
            field=models.TextField(blank=True, null=True),
        ),
    ]
