# Generated by Django 5.2.1 on 2025-09-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0011_alter_gamescores_all_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescores',
            name='all_symbol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='tc_symbol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='user_symbol',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
