# Generated by Django 5.2.1 on 2025-09-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0012_alter_gamescores_all_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='meta_curve',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
