# Generated by Django 5.2.1 on 2025-09-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0013_gameinfo_meta_curve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewinfo',
            name='metascore',
            field=models.IntegerField(null=True),
        ),
    ]
