# Generated by Django 5.2.1 on 2025-09-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0014_reviewinfo_metascore'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewinfo',
            name='is_meta',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
