# Generated by Django 5.2.1 on 2025-09-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0015_reviewinfo_is_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewinfo',
            name='is_meta',
        ),
    ]
