# Generated by Django 5.2.1 on 2025-09-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0016_remove_reviewinfo_is_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='meta_curve',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
