# Generated by Django 5.2.1 on 2025-10-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0018_reviewinfo_is_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReviewInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('date_published', models.DateField()),
                ('user', models.TextField()),
                ('is_user', models.IntegerField()),
            ],
        ),
    ]
