# Generated by Django 5.2.1 on 2025-10-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0019_userreviewinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviewinfo',
            name='game',
            field=models.IntegerField(null=True),
        ),
    ]
