# Generated by Django 5.2.1 on 2025-10-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0020_userreviewinfo_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReviewInfo',
        ),
    ]
