# Generated by Django 5.2.1 on 2025-10-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0022_userreviewinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReviewInfo',
        ),
    ]
