# Generated by Django 5.2.1 on 2025-10-14 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0023_delete_userreviewinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReviewInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('date_published', models.DateField()),
                ('user', models.TextField()),
                ('is_user', models.IntegerField()),
                ('platform', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newGameoMeter.gameinfo')),
            ],
        ),
    ]
