# Generated by Django 5.2.1 on 2025-12-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0024_userreviewinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField()),
                ('games', models.ManyToManyField(blank=True, to='newGameoMeter.gameinfo')),
            ],
        ),
    ]
