# Generated by Django 6.0.3 on 2026-03-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0025_gametag'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='cached_gm',
            field=models.IntegerField(blank=True, default='-1', null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='cached_user',
            field=models.IntegerField(blank=True, default='-1', null=True),
        ),
    ]
