# Generated by Django 6.0.3 on 2026-03-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0026_gameinfo_cached_gm_gameinfo_cached_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='cached_meta',
            field=models.IntegerField(blank=True, default='-1', null=True),
        ),
    ]
