# Generated by Django 6.0.3 on 2026-03-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0027_gameinfo_cached_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='cached_cf',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
