# Generated by Django 6.0.3 on 2026-03-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0028_gameinfo_cached_cf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='cached_cf',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
