# Generated by Django 6.0.3 on 2026-03-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0029_alter_gameinfo_cached_cf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametag',
            name='games',
        ),
    ]
