# Generated by Django 6.0.3 on 2026-03-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0030_remove_gametag_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='tag_list',
            field=models.ManyToManyField(to='newGameoMeter.gametag'),
        ),
    ]
