# Generated by Django 6.0.3 on 2026-03-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0031_gameinfo_tag_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='tag_list',
            field=models.ManyToManyField(related_name='tags', to='newGameoMeter.gametag'),
        ),
    ]
