# Generated by Django 5.2.1 on 2026-04-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0032_alter_gameinfo_tag_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='cached_ave',
            field=models.FloatField(blank=True, default='-1.0', null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='cached_num_fresh',
            field=models.IntegerField(blank=True, default='-1', null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='cached_num_rotten',
            field=models.IntegerField(blank=True, default='-1', null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='cached_user_ave',
            field=models.FloatField(blank=True, default='-1.0', null=True),
        ),
    ]
