# Generated by Django 5.2.1 on 2026-04-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0033_gameinfo_cached_ave_gameinfo_cached_num_fresh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='json_info',
            field=models.JSONField(default={}, verbose_name='JSONInfo'),
        ),
    ]
