# Generated by Django 5.2.1 on 2026-04-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGameoMeter', '0035_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='alt_names',
        ),
        migrations.AddField(
            model_name='publication',
            name='main_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newGameoMeter.publication'),
        ),
    ]
